// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJztEjXh_AHYOa_WsDVIr6I7mKblVKcA',
    appId: '1:292763435916:web:fcac578ae61aac90668ca9',
    messagingSenderId: '292763435916',
    projectId: 'food-4df16',
    authDomain: 'food-4df16.firebaseapp.com',
    storageBucket: 'food-4df16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdveec6TbXaCZhOyd1MahNKZw7OJSBK7A',
    appId: '1:292763435916:android:eef8276a09fa4459668ca9',
    messagingSenderId: '292763435916',
    projectId: 'food-4df16',
    storageBucket: 'food-4df16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTyBnQYQqBMoJdxyzpYKbGd97iNPts4XA',
    appId: '1:292763435916:ios:76b9c0b9302c0691668ca9',
    messagingSenderId: '292763435916',
    projectId: 'food-4df16',
    storageBucket: 'food-4df16.appspot.com',
    iosBundleId: 'com.example.microbiocol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTyBnQYQqBMoJdxyzpYKbGd97iNPts4XA',
    appId: '1:292763435916:ios:76b9c0b9302c0691668ca9',
    messagingSenderId: '292763435916',
    projectId: 'food-4df16',
    storageBucket: 'food-4df16.appspot.com',
    iosBundleId: 'com.example.microbiocol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOJztEjXh_AHYOa_WsDVIr6I7mKblVKcA',
    appId: '1:292763435916:web:fc78273811f68165668ca9',
    messagingSenderId: '292763435916',
    projectId: 'food-4df16',
    authDomain: 'food-4df16.firebaseapp.com',
    storageBucket: 'food-4df16.appspot.com',
  );
}
